server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: nacos-consumer
          uri: lb://nacos-consumer
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer(?<segment>/?.*), $\{segment}
        - id: nacos-producer
          uri: lb://nacos-producer
          predicates:
            - Path=/producer/**
          filters:
            - RewritePath=/producer(?<segment>/?.*), $\{segment}
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-gateway